#!/usr/bin/env python
# coding: utf-8

# <h1>My Jupyter Notebook on IBM Watson Studio

# <strong>Anbu Selvan T</strong>

# Human 100%

# <i>I am interested in data science because i likeplaying  with data and finding pattern </i>

# <h3> The following code will add multiply numbers</h3>

# In[5]:


num1 = 1.5
num2 = 6.3

# Add two numbers
mul = num1 * num2

# Display the sum
print('The multiple of {0} and {1} is {2}'.format(num1, num2, mul))


# <ul>
#   <li>Car</li>
#   <li>Bike</li>
#   <li>Cycyle</li>
# </ul>

# <ol>
#   <li>Car</li>
#   <li>Bike</li>
#   <li>Cycle</li>
# </ol>

# <a href="url">test_link text</a>

# In[ ]:
